export const CREATE_GROUP = "CREATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const SELECT_GROUP = "SELECT_GROUP";
export const RESET_GROUP = "RESET_GROUP";

export const CREATE_CONTACT = "CREATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SELECT_CONTACT = "SELECT_CONTACT";
export const RESET_CONTACT = "RESET_CONTACT";
